'use client';
import { ChevronDown, FileText, GitCompareArrows, ListFilter, Plus, Search, UploadCloud } from 'lucide-react';
import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { StatusPill } from '@/components/status-pill';
import { revisions as demoRevisions } from '@/lib/demo-data';
import type { DocumentRevision } from '@/lib/types';
import { api } from '@/lib/api';
import { uploadProjectFile } from '@/lib/uploads';
import { uploadedRevisionRow, type RevisionCreationResult } from '@/lib/document-revisions';

export default function DocumentsPage() {
  const {demo,organizationId,projectId}=useWorkspace();const[revisions,setRevisions]=useState<DocumentRevision[]>(demo?demoRevisions:[]);const[error,setError]=useState('');const[uploading,setUploading]=useState(false);const[query,setQuery]=useState('');const[discipline,setDiscipline]=useState('all');const[status,setStatus]=useState('all');const fileInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(demo){setRevisions(demoRevisions);return}if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<Array<{id:string;title:string;discipline:string;revisions:Array<{id:string;revision:string;status:string;sheet_number:string|null;issue_date:string|null;created_at:string}>}>>(`/projects/${projectId}/documents`).then(documents=>{if(active)setRevisions(documents.flatMap(document=>document.revisions.map(revision=>({id:revision.id,sheet:revision.sheet_number||'--',title:document.title,discipline:document.discipline||'General',revision:revision.revision,status:revisionStatus(revision.status),issuedAt:new Date(revision.issue_date||revision.created_at).toLocaleDateString(),linkedIssues:0}))))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Documents could not be loaded.')});return()=>{active=false}},[demo,projectId]);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;event.target.value='';if(demo){setError('Demo workspace uploads are disabled. Create a workspace to process your own drawing set.');return}setUploading(true);setError('');try{const uploaded=await uploadProjectFile(organizationId,projectId,file);const document=await api.post<{id:string}>(`/projects/${projectId}/documents`,{title:file.name.replace(/\.[^.]+$/,''),kind:'drawing',discipline:'general'});const created=await api.post<RevisionCreationResult>(`/documents/${document.id}/revisions`,{upload_id:uploaded.id,revision:'uploaded',status:'uploaded',sheet_number:null,metadata_json:{source:'web_upload'},process:true});setRevisions(current=>[uploadedRevisionRow(created,file.name),...current])}catch(cause){setError(cause instanceof Error?cause.message:'The document could not be uploaded.')}finally{setUploading(false)}}
  const visibleRevisions=useMemo(()=>revisions.filter(revision=>{const needle=query.trim().toLowerCase();return(discipline==='all'||revision.discipline===discipline)&&(status==='all'||revision.status===status)&&(!needle||`${revision.sheet} ${revision.title} ${revision.revision}`.toLowerCase().includes(needle))}),[discipline,query,revisions,status]);
  return <div className="page-pad"><input ref={fileInput} hidden type="file" accept=".pdf,.ifc,.doc,.docx,.xls,.xlsx,image/*" onChange={upload}/><PageHeader title="Documents & revisions" description="The version-aware project record behind every BUILI verification." actions={<><button className="button button--secondary" disabled title="Select two revisions from a sheet before comparing"><GitCompareArrows size={14}/> Compare revisions</button><button className="button button--primary" onClick={()=>fileInput.current?.click()} disabled={uploading}><UploadCloud size={14}/> {uploading?'Uploading...':'Upload documents'}</button></>}/>
    <section className="document-health"><div><span>Current drawing set</span><strong>{demo?'Rev set 2026.07.11':`${revisions.filter(item=>item.status==='Current').length} current`}</strong><small>{demo?'31 sheets / 4 disciplines':'Approved and current revisions'}</small></div><div><span>Review required</span><strong>{String(revisions.filter(item=>item.status==='Review required').length).padStart(2,'0')}</strong><small>Metadata or precedence unresolved</small></div><div><span>Processing</span><strong>{String(revisions.filter(item=>item.status==='Processing').length).padStart(2,'0')}</strong><small>{demo?'FP-202 / 68% complete':'Background extraction jobs'}</small></div><div><span>Superseded sources</span><strong>{demo?'47':String(revisions.filter(item=>item.status==='Superseded').length).padStart(2,'0')}</strong><small>Retained for traceability</small></div></section>
    <div className="document-tabs"><button className="active" aria-pressed="true" disabled>Drawing sets</button>{['Specifications','RFIs','Submittals','Field instructions','All files'].map(name=><button key={name} disabled title={`${name} are available when that source type is loaded`}>{name}</button>)}</div>
    <div className="filter-row"><div className="table-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search sheet or title" placeholder="Search sheet or title"/></div><select className="filter-button" value={discipline} onChange={event=>setDiscipline(event.target.value)} aria-label="Filter by discipline"><option value="all">All disciplines</option>{Array.from(new Set(revisions.map(item=>item.discipline))).map(item=><option key={item}>{item}</option>)}</select><select className="filter-button" value={status} onChange={event=>setStatus(event.target.value)} aria-label="Filter by status"><option value="all">Any status</option>{Array.from(new Set(revisions.map(item=>item.status))).map(item=><option key={item}>{item}</option>)}</select><span className="filter-spacer"/><button className="filter-button" onClick={()=>{setQuery('');setDiscipline('all');setStatus('all')}}><ListFilter/> Reset filters</button><button className="filter-button" disabled title="Create source relationships from a selected document revision"><Plus/> Add source relationship</button></div>
    {error&&<p className="inline-error" role="alert">{error}</p>}<div className="table-scroll"><table className="data-table document-table"><thead><tr><th>Sheet</th><th>Title</th><th>Discipline</th><th>Revision</th><th>Status</th><th>Issued</th><th>Linked issues</th><th/></tr></thead><tbody>{visibleRevisions.map(rev=><tr key={rev.id}><td><span className="document-icon"><FileText/></span><b className="mono">{rev.sheet}</b></td><td><b>{rev.title}</b></td><td className="cell-muted">{rev.discipline}</td><td><b className="revision-badge">{rev.revision}</b></td><td><StatusPill tone={rev.status==='Current'?'green':rev.status==='Review required'?'amber':rev.status==='Processing'?'blue':'neutral'}>{rev.status}</StatusPill></td><td className="cell-muted">{rev.issuedAt}</td><td><span className="linked-count">{rev.linkedIssues}</span></td><td><button className="icon-button" disabled title="Select a document to view available actions" aria-label={`More actions for ${rev.sheet}`}>•••</button></td></tr>)}</tbody></table>{visibleRevisions.length===0&&!error&&<div className="live-placeholder"><Search/><p><b>No matching document revisions.</b><span>Clear the search or choose another filter.</span></p></div>}</div>
    <section className="upload-zone"><UploadCloud/><div><b>Upload a drawing set or project document</b><span>PDF, IFC, images, DOCX, XLSX / files upload directly to configured private storage</span></div><button className="button button--secondary" onClick={()=>fileInput.current?.click()} disabled={uploading}>Choose files</button></section>
  </div>;
}
function revisionStatus(value:string):DocumentRevision['status']{const normalized=value.toLowerCase();if(normalized==='current'||normalized==='approved')return'Current';if(normalized==='review_required')return'Review required';if(normalized==='processing'||normalized==='uploaded')return'Processing';return'Superseded'}
