'use client';
import { ChevronDown, FileText, GitCompareArrows, ListFilter, Plus, Search, UploadCloud } from 'lucide-react';
import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { StatusPill } from '@/components/status-pill';
import { revisions as demoRevisions } from '@/lib/demo-data';
import type { DocumentRevision } from '@/lib/types';
import { api } from '@/lib/api';
import { uploadProjectFile } from '@/lib/uploads';

export default function DocumentsPage() {
  const {demo,organizationId,projectId}=useWorkspace();const[revisions,setRevisions]=useState<DocumentRevision[]>(demo?demoRevisions:[]);const[error,setError]=useState('');const[uploading,setUploading]=useState(false);const fileInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(demo){setRevisions(demoRevisions);return}if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<Array<{id:string;title:string;discipline:string;revisions:Array<{id:string;revision:string;status:string;sheet_number:string|null;issue_date:string|null;created_at:string}>}>>(`/projects/${projectId}/documents`).then(documents=>{if(active)setRevisions(documents.flatMap(document=>document.revisions.map(revision=>({id:revision.id,sheet:revision.sheet_number||'--',title:document.title,discipline:document.discipline||'General',revision:revision.revision,status:revisionStatus(revision.status),issuedAt:new Date(revision.issue_date||revision.created_at).toLocaleDateString(),linkedIssues:0}))))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Documents could not be loaded.')});return()=>{active=false}},[demo,projectId]);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;event.target.value='';if(demo){setError('Demo workspace uploads are disabled. Create a workspace to process your own drawing set.');return}setUploading(true);setError('');try{const uploaded=await uploadProjectFile(organizationId,projectId,file);const document=await api.post<{id:string}>(`/projects/${projectId}/documents`,{title:file.name.replace(/\.[^.]+$/,''),kind:'drawing',discipline:'general'});const revision=await api.post<{id:string;revision:string;status:string;sheet_number:string|null;created_at:string}>(`/documents/${document.id}/revisions`,{upload_id:uploaded.id,revision:'uploaded',status:'uploaded',sheet_number:null,metadata_json:{source:'web_upload'},process:true});setRevisions(current=>[{id:revision.id,sheet:revision.sheet_number||'--',title:file.name,discipline:'General',revision:revision.revision,status:'Processing',issuedAt:new Date(revision.created_at).toLocaleDateString(),linkedIssues:0},...current])}catch(cause){setError(cause instanceof Error?cause.message:'The document could not be uploaded.')}finally{setUploading(false)}}
  return <div className="page-pad"><input ref={fileInput} hidden type="file" accept=".pdf,.ifc,.doc,.docx,.xls,.xlsx,image/*" onChange={upload}/><PageHeader title="Documents & revisions" description="The version-aware project record behind every BUILI verification." actions={<><button className="button button--secondary"><GitCompareArrows size={14}/> Compare revisions</button><button className="button button--primary" onClick={()=>fileInput.current?.click()} disabled={uploading}><UploadCloud size={14}/> {uploading?'Uploading...':'Upload documents'}</button></>}/>
    <section className="document-health"><div><span>Current drawing set</span><strong>{demo?'Rev set 2026.07.11':`${revisions.filter(item=>item.status==='Current').length} current`}</strong><small>{demo?'31 sheets / 4 disciplines':'Approved and current revisions'}</small></div><div><span>Review required</span><strong>{String(revisions.filter(item=>item.status==='Review required').length).padStart(2,'0')}</strong><small>Metadata or precedence unresolved</small></div><div><span>Processing</span><strong>{String(revisions.filter(item=>item.status==='Processing').length).padStart(2,'0')}</strong><small>{demo?'FP-202 / 68% complete':'Background extraction jobs'}</small></div><div><span>Superseded sources</span><strong>{demo?'47':String(revisions.filter(item=>item.status==='Superseded').length).padStart(2,'0')}</strong><small>Retained for traceability</small></div></section>
    <div className="document-tabs"><button className="active">Drawing sets</button><button>Specifications</button><button>RFIs</button><button>Submittals</button><button>Field instructions</button><button>All files</button></div>
    <div className="filter-row"><div className="table-search"><Search/><input placeholder="Search sheet or title"/></div><button className="filter-button"><ListFilter/> All disciplines</button><button className="filter-button">Any status <ChevronDown/></button><span className="filter-spacer"/><button className="filter-button"><Plus/> Add source relationship</button></div>
    {error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table document-table"><thead><tr><th>Sheet</th><th>Title</th><th>Discipline</th><th>Revision</th><th>Status</th><th>Issued</th><th>Linked issues</th><th/></tr></thead><tbody>{revisions.map(rev=><tr key={rev.id}><td><span className="document-icon"><FileText/></span><b className="mono">{rev.sheet}</b></td><td><b>{rev.title}</b></td><td className="cell-muted">{rev.discipline}</td><td><b className="revision-badge">{rev.revision}</b></td><td><StatusPill tone={rev.status==='Current'?'green':rev.status==='Review required'?'amber':rev.status==='Processing'?'blue':'neutral'}>{rev.status}</StatusPill></td><td className="cell-muted">{rev.issuedAt}</td><td><span className="linked-count">{rev.linkedIssues}</span></td><td><button className="icon-button" aria-label={`More actions for ${rev.sheet}`}>•••</button></td></tr>)}</tbody></table></div>
    <section className="upload-zone"><UploadCloud/><div><b>Upload a drawing set or project document</b><span>PDF, IFC, images, DOCX, XLSX / files upload directly to configured private storage</span></div><button className="button button--secondary" onClick={()=>fileInput.current?.click()} disabled={uploading}>Choose files</button></section>
  </div>;
}
function revisionStatus(value:string):DocumentRevision['status']{const normalized=value.toLowerCase();if(normalized==='current'||normalized==='approved')return'Current';if(normalized==='review_required')return'Review required';if(normalized==='processing'||normalized==='uploaded')return'Processing';return'Superseded'}
