'use client';
import Link from 'next/link';
import { ChevronDown, Download, ListFilter, Plus, Search } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { Discipline, StatusPill } from '@/components/status-pill';
import { issues as demoIssues } from '@/lib/demo-data';
import type { Issue } from '@/lib/types';
import { api } from '@/lib/api';

type IssueRow = Issue & {routeId?:string};
export default function IssuesPage(){const {demo,projectId}=useWorkspace();const [issues,setIssues]=useState<IssueRow[]>(demo?demoIssues:[]);const [error,setError]=useState('');useEffect(()=>{if(demo){setIssues(demoIssues);return}if(!projectId||projectId==='loading'||projectId==='none')return;let active=true;api.get<Array<{id:string;number:string;title:string;issue_type:string;status:string;priority:string;assigned_to:string|null;location_json:Record<string,unknown>;updated_at:string}>>(`/projects/${projectId}/issues`).then(rows=>{if(active)setIssues(rows.map(row=>({id:row.number,routeId:row.id,title:row.title,type:actionLabel(row.issue_type),discipline:'ARCH',location:Object.values(row.location_json||{}).filter(value=>typeof value==='string').join(' / ')||'Location not assigned',status:statusLabel(row.status),priority:priorityLabel(row.priority),assignee:row.assigned_to||'Unassigned',updatedAt:new Date(row.updated_at).toLocaleDateString()})))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Issues could not be loaded.')});return()=>{active=false}},[demo,projectId]);return <div className="page-pad"><PageHeader title="Issues" description="Track each field observation from evidence gathering through review, action, and closeout." actions={<><button className="button button--secondary"><Download size={14}/> Export</button><button className="button button--primary"><Plus size={14}/> New issue</button></>}/>
  <div className="issue-status-strip"><button className="active"><b>{String(issues.filter(item=>item.status!=='Closed').length).padStart(2,'0')}</b><span>All open</span></button><button><b>{String(issues.filter(item=>item.status==='Evidence required').length).padStart(2,'0')}</b><span>Evidence required</span></button><button><b>{String(issues.filter(item=>item.status==='Ready for review').length).padStart(2,'0')}</b><span>Ready for review</span></button><button><b>{String(issues.filter(item=>item.status==='Issued').length).padStart(2,'0')}</b><span>Issued</span></button><button><b>{demo?'02':'—'}</b><span>Due this week</span></button></div>
  <div className="filter-row"><div className="table-search"><Search/><input placeholder="Search issue or location"/></div><button className="filter-button"><ListFilter/> All actions</button><button className="filter-button">All disciplines <ChevronDown/></button><button className="filter-button">All assignees <ChevronDown/></button><span className="filter-spacer"/><button className="filter-button">Updated <ChevronDown/></button></div>
  {error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table issue-table"><thead><tr><th>ID</th><th>Issue</th><th>Location</th><th>Action</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Updated</th></tr></thead><tbody>{issues.map(issue=><tr key={issue.routeId||issue.id}><td className="cell-id">{issue.id}</td><td className="cell-title"><Link href={`/app/issues/${issue.routeId||issue.id}${demo?'?demo=1':''}`}>{issue.title}</Link><small><Discipline value={issue.discipline}/></small></td><td className="cell-muted">{issue.location}</td><td>{issue.type}</td><td><StatusPill tone={tone(issue.status)}>{issue.status}</StatusPill></td><td><span className={`priority priority--${issue.priority.toLowerCase()}`}><i/>{issue.priority}</span></td><td className="cell-muted">{issue.assignee}</td><td className="cell-muted">{issue.updatedAt}</td></tr>)}</tbody></table></div>
 </div>}
function tone(status:string):'green'|'amber'|'blue'|'neutral'{if(status==='Ready for review')return'green';if(status==='Evidence required')return'amber';if(status==='Issued')return'blue';return'neutral'}
function titleCase(value:string){return value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function statusLabel(value:string):Issue['status']{const label=titleCase(value);if(label==='Ready For Review')return'Ready for review';if(label==='Evidence Required')return'Evidence required';if(label==='Issued')return'Issued';if(label==='Closed')return'Closed';return'Open'}
function priorityLabel(value:string):Issue['priority']{const label=titleCase(value);return (['Critical','High','Medium','Low'].includes(label)?label:label==='Normal'?'Medium':'Low') as Issue['priority']}
function actionLabel(value:string):Issue['type']{const label=titleCase(value);if(label.includes('Punch'))return'Punch';if(label.includes('Change'))return'Change event';if(label.includes('Model'))return'Model update';return'RFI candidate'}
