'use client';
import Link from 'next/link';
import { ChevronDown, Download, ListFilter, Plus, Search } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { Discipline, StatusPill } from '@/components/status-pill';
import { issues as demoIssues } from '@/lib/demo-data';
import type { Issue } from '@/lib/types';
import { api } from '@/lib/api';
import { downloadCsv } from '@/lib/csv';

type IssueRow = Issue & {routeId?:string};
export default function IssuesPage(){const {demo,projectId}=useWorkspace();const [issues,setIssues]=useState<IssueRow[]>(demo?demoIssues:[]);const [error,setError]=useState('');const[query,setQuery]=useState('');const[statusFilter,setStatusFilter]=useState('open');const[actionFilter,setActionFilter]=useState('all');useEffect(()=>{if(demo){setIssues(demoIssues);return}if(!projectId||projectId==='loading'||projectId==='none')return;let active=true;api.get<Array<{id:string;number:string;title:string;issue_type:string;status:string;priority:string;assigned_to:string|null;location_json:Record<string,unknown>;updated_at:string}>>(`/projects/${projectId}/issues`).then(rows=>{if(active)setIssues(rows.map(row=>({id:row.number,routeId:row.id,title:row.title,type:actionLabel(row.issue_type),discipline:'ARCH',location:Object.values(row.location_json||{}).filter(value=>typeof value==='string').join(' / ')||'Location not assigned',status:statusLabel(row.status),priority:priorityLabel(row.priority),assignee:row.assigned_to||'Unassigned',updatedAt:new Date(row.updated_at).toLocaleDateString()})))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Issues could not be loaded.')});return()=>{active=false}},[demo,projectId]);const visibleIssues=useMemo(()=>issues.filter(issue=>{const needle=query.trim().toLowerCase();const statusMatches=statusFilter==='all'||(statusFilter==='open'&&issue.status!=='Closed')||issue.status===statusFilter;const actionMatches=actionFilter==='all'||issue.type===actionFilter;return statusMatches&&actionMatches&&(!needle||`${issue.id} ${issue.title} ${issue.location} ${issue.assignee}`.toLowerCase().includes(needle))}),[actionFilter,issues,query,statusFilter]);function exportIssues(){downloadCsv('buili-issue-log.csv',['ID','Issue','Location','Action','Status','Priority','Assignee','Updated'],visibleIssues.map(issue=>[issue.id,issue.title,issue.location,issue.type,issue.status,issue.priority,issue.assignee,issue.updatedAt]))}return <div className="page-pad"><PageHeader title="Issues" description="Track each field observation from evidence gathering through review, action, and closeout." actions={<><button className="button button--secondary" onClick={exportIssues} disabled={visibleIssues.length===0}><Download size={14}/> Export</button><Link className="button button--primary" href="/app/capture"><Plus size={14}/> New issue</Link></>}/>
  <div className="issue-status-strip"><button className={statusFilter==='open'?'active':''} aria-pressed={statusFilter==='open'} onClick={()=>setStatusFilter('open')}><b>{String(issues.filter(item=>item.status!=='Closed').length).padStart(2,'0')}</b><span>All open</span></button><button className={statusFilter==='Evidence required'?'active':''} aria-pressed={statusFilter==='Evidence required'} onClick={()=>setStatusFilter('Evidence required')}><b>{String(issues.filter(item=>item.status==='Evidence required').length).padStart(2,'0')}</b><span>Evidence required</span></button><button className={statusFilter==='Ready for review'?'active':''} aria-pressed={statusFilter==='Ready for review'} onClick={()=>setStatusFilter('Ready for review')}><b>{String(issues.filter(item=>item.status==='Ready for review').length).padStart(2,'0')}</b><span>Ready for review</span></button><button className={statusFilter==='Issued'?'active':''} aria-pressed={statusFilter==='Issued'} onClick={()=>setStatusFilter('Issued')}><b>{String(issues.filter(item=>item.status==='Issued').length).padStart(2,'0')}</b><span>Issued</span></button><button disabled title="Due-date filtering becomes available when issue schedules are loaded"><b>{demo?'02':'—'}</b><span>Due this week</span></button></div>
  <div className="filter-row"><div className="table-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} aria-label="Search issue or location" placeholder="Search issue or location"/></div><select className="filter-button" value={actionFilter} onChange={event=>setActionFilter(event.target.value)} aria-label="Filter by action"><option value="all">All actions</option>{Array.from(new Set(issues.map(issue=>issue.type))).map(action=><option key={action}>{action}</option>)}</select><span className="filter-spacer"/><button className="filter-button" onClick={()=>{setQuery('');setStatusFilter('open');setActionFilter('all')}}><ListFilter/> Reset filters</button></div>
  {error&&<p className="inline-error" role="alert">{error}</p>}<div className="table-scroll"><table className="data-table issue-table"><thead><tr><th>ID</th><th>Issue</th><th>Location</th><th>Action</th><th>Status</th><th>Priority</th><th>Assignee</th><th>Updated</th></tr></thead><tbody>{visibleIssues.map(issue=><tr key={issue.routeId||issue.id}><td className="cell-id">{issue.id}</td><td className="cell-title"><Link href={`/app/issues/${issue.routeId||issue.id}${demo?'?demo=1':''}`}>{issue.title}</Link><small><Discipline value={issue.discipline}/></small></td><td className="cell-muted">{issue.location}</td><td>{issue.type}</td><td><StatusPill tone={tone(issue.status)}>{issue.status}</StatusPill></td><td><span className={`priority priority--${issue.priority.toLowerCase()}`}><i/>{issue.priority}</span></td><td className="cell-muted">{issue.assignee}</td><td className="cell-muted">{issue.updatedAt}</td></tr>)}</tbody></table>{visibleIssues.length===0&&!error&&<div className="live-placeholder"><Search/><p><b>No matching issues.</b><span>Clear the search or choose another status.</span></p></div>}</div>
 </div>}
function tone(status:string):'green'|'amber'|'blue'|'neutral'{if(status==='Ready for review')return'green';if(status==='Evidence required')return'amber';if(status==='Issued')return'blue';return'neutral'}
function titleCase(value:string){return value.toLowerCase().replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}
function statusLabel(value:string):Issue['status']{const label=titleCase(value);if(label==='Ready For Review')return'Ready for review';if(label==='Evidence Required')return'Evidence required';if(label==='Issued')return'Issued';if(label==='Closed')return'Closed';return'Open'}
function priorityLabel(value:string):Issue['priority']{const label=titleCase(value);return (['Critical','High','Medium','Low'].includes(label)?label:label==='Normal'?'Medium':'Low') as Issue['priority']}
function actionLabel(value:string):Issue['type']{const label=titleCase(value);if(label.includes('Punch'))return'Punch';if(label.includes('Change'))return'Change event';if(label.includes('Model'))return'Model update';return'RFI candidate'}
