'use client';
import { Check, Download, FileText, Mail, MoreHorizontal, Printer, Save, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import { StatusPill } from '@/components/status-pill';
import { useWorkspace } from '@/components/demo-mode';
import { PageHeader } from '@/components/page-header';
import { api } from '@/lib/api';

export default function ReportsPage(){const{demo,projectId}=useWorkspace();if(!demo)return <LiveReports projectId={projectId}/>;return <div className="reports-workspace"><aside className="report-list"><div className="panel-title"><b>Reports</b><button><MoreHorizontal/></button></div><div className="report-group"><h3>Ready for review</h3><button className="active"><span>Punch item / P-024</span><b>Garage GFCI correction</b><small>Updated 4 min ago</small></button><button><span>RFI draft / RFI-018</span><b>Partition dimension conflict</b><small>Updated 31 min ago</small></button></div><div className="report-group"><h3>Issued</h3><button><span>RFI / RFI-017</span><b>HVAC north corridor route</b><small>Issued yesterday</small></button><button><span>Change evidence / CE-007</span><b>Existing footing condition</b><small>Issued Jul 10</small></button></div></aside>
  <main className="report-preview-area"><div className="report-toolbar"><span>Original layout · Version 3</span><div><button><Printer/> Print</button><a href="/demo/BUI-1042-issue-package.pdf" target="_blank" rel="noreferrer"><Download/> PDF</a><button><Mail/> Share</button></div></div><article className="report-sheet">
    <header className="report-brand"><div><img src="/brand/buili-logo.png" alt="BUILI"/><span>VERIFIED FIELD ACTION</span></div><p>NORTHSTAR BUILDERS<br/><b>COOPER RESIDENCE RENOVATION</b></p></header>
    <div className="report-title-block"><span>PUNCH ITEM · P-024</span><h1>Garage GFCI receptacle below required elevation</h1><p>Prepared from field issue BUI-1042 · July 12, 2026</p></div>
    <div className="report-meta"><div><span>Location</span><b>Garage · East wall · Entry door</b></div><div><span>Responsible trade</span><b>Delta Electrical</b></div><div><span>Due before</span><b>Wall close-in · July 14</b></div><div><span>Status</span><StatusPill tone="green">Ready for review</StatusPill></div></div>
    <section className="report-finding"><h2>Verified finding</h2><p>The installed GFCI receptacle centerline measures <strong>12 in. above finished floor</strong>. E1.1 Electrical Note 3 requires garage receptacles at a minimum of <strong>18 in. above finished floor</strong>.</p><div><span>Observed<strong>12 in. AFF</strong></span><i>→</i><span>Required<strong>18 in. AFF min.</strong></span><em>−6 in.</em></div></section>
    <section className="report-action"><h2>Required action</h2><p>Raise the garage east-wall GFCI receptacle box to a minimum centerline elevation of 18 in. AFF before wall close-in. Upload one completion photograph with a visible measurement for verification.</p></section>
    <section className="report-evidence-strip"><h2>Field evidence</h2><div><figure><img src="/demo/garage-east-wall-context-thumb.webp" alt="Garage east wall context"/><figcaption>01 · Room context</figcaption></figure><figure><img src="/demo/receptacle-rough-in-detail-thumb.webp" alt="GFCI rough-in detail"/><figcaption>02 · Installation detail</figcaption></figure><figure><img src="/demo/box-elevation-measurement-thumb.webp" alt="Box elevation measurement"/><figcaption>03 · Dimension proof</figcaption></figure></div></section>
    <section className="report-source"><FileText/><div><span>CONTROLLING SOURCE</span><b>E1.1 · REV 03 · ELECTRICAL NOTE 3</b><p>“Garage receptacles: mount at 18 in. AFF minimum unless noted otherwise.”</p></div><Check/></section>
    <footer className="report-footer"><span>Source-cited draft · Not issued until approved</span><span>BUILI / P-024 / V3</span></footer>
  </article></main>
  <aside className="report-review"><div className="panel-title"><b>Review & issue</b><button><MoreHorizontal/></button></div><div className="review-scroll"><section><h3>Approval</h3><StatusPill tone="green">Evidence sufficient</StatusPill><p>Sources, location, measurement, and recommended action are complete.</p></section><section><h3>Prepared by</h3><div className="review-person"><span>JC</span><p><b>Jordan Cho</b><small>Project Manager</small></p></div></section><section><h3>Revision note</h3><textarea defaultValue="Verified field correction before wall close-in."/></section><section><h3>Destinations</h3><label><input type="checkbox" defaultChecked/> Project issue log</label><label><input type="checkbox" defaultChecked/> Delta Electrical</label><label><input type="checkbox"/> Procore export</label></section></div><div className="review-actions"><button className="button button--secondary"><Save/> Save version</button><button className="button button--primary"><Send/> Approve & issue</button></div></aside>
 </div>}

type LiveReport={id:string;kind:string;status:string;version:number;title:string;created_at:string};
function LiveReports({projectId}:{projectId:string}){const[reports,setReports]=useState<LiveReport[]>([]);const[error,setError]=useState('');useEffect(()=>{if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<LiveReport[]>(`/projects/${projectId}/reports`).then(rows=>{if(active)setReports(rows)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Reports could not be loaded.')});return()=>{active=false}},[projectId]);async function openReport(id:string){try{const result=await api.get<{report:LiveReport;download_url:string}>(`/reports/${id}`);window.open(result.download_url,'_blank','noopener,noreferrer')}catch(cause){setError(cause instanceof Error?cause.message:'Report could not be opened.')}}return <div className="page-pad"><PageHeader title="Reports" description="Versioned, source-cited project outputs generated from approved issues."/>{error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Report</th><th>Kind</th><th>Status</th><th>Version</th><th>Created</th><th/></tr></thead><tbody>{reports.map(report=><tr key={report.id}><td className="cell-title"><b>{report.title}</b><small className="cell-id">{report.id}</small></td><td>{report.kind.replaceAll('_',' ')}</td><td><StatusPill tone={report.status==='approved'?'green':'neutral'}>{report.status}</StatusPill></td><td className="cell-id">v{report.version}</td><td className="cell-muted">{new Date(report.created_at).toLocaleString()}</td><td><button className="button button--secondary button--small" onClick={()=>openReport(report.id)}><Download/> Open</button></td></tr>)}</tbody></table></div>{reports.length===0&&!error&&<div className="live-placeholder"><FileText/><p><b>No reports have been generated.</b><span>Approve an issue, then generate an RFI, punch, change event, or evidence package.</span></p></div>}</div>}
