'use client';
import { Check, Download, FileText, Mail, MoreHorizontal, Printer, Save, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import { StatusPill } from '@/components/status-pill';
import { useWorkspace } from '@/components/demo-mode';
import { PageHeader } from '@/components/page-header';
import { api } from '@/lib/api';

const demoReports=[
  {id:'P-024',kind:'Punch item',title:'Garage GFCI correction',status:'Ready for review',updated:'Updated 4 min ago'},
  {id:'RFI-018',kind:'RFI draft',title:'Partition dimension conflict',status:'Draft',updated:'Updated 31 min ago'},
  {id:'RFI-017',kind:'RFI',title:'HVAC north corridor route',status:'Issued',updated:'Issued yesterday'},
  {id:'CE-007',kind:'Change evidence',title:'Existing footing condition',status:'Issued',updated:'Issued Jul 10'}
];

export default function ReportsPage(){const{demo,projectId}=useWorkspace();const[selectedId,setSelectedId]=useState('P-024');const[version,setVersion]=useState(3);const[issued,setIssued]=useState(false);const[message,setMessage]=useState('');const[revisionNote,setRevisionNote]=useState('Verified field correction before wall close-in.');if(!demo)return <LiveReports projectId={projectId}/>;const selected=demoReports.find(report=>report.id===selectedId)||demoReports[0];async function shareReport(){setMessage('');const shareData={title:`${selected.kind} ${selected.id} — ${selected.title}`,text:`BUILI demo report: ${selected.title}`,url:selected.id==='P-024'?`${window.location.origin}/demo/BUI-1042-issue-package.pdf`:window.location.href};try{if(navigator.share)await navigator.share(shareData);else if(navigator.clipboard){await navigator.clipboard.writeText(shareData.url);setMessage('Report link copied to clipboard.')}else setMessage('Sharing is not supported in this browser.')}catch(cause){if((cause as DOMException)?.name!=='AbortError')setMessage('The report could not be shared.')}}function saveVersion(){setVersion(value=>value+1);setMessage(`Demo version ${version+1} saved for this browser session.`)}return <div className="reports-workspace"><aside className="report-list"><div className="panel-title"><b>Reports</b><button disabled title="Additional report actions are unavailable in the demo" aria-label="Additional report actions"><MoreHorizontal/></button></div><div className="report-group"><h3>Ready for review</h3>{demoReports.filter(report=>report.status!=='Issued').map(report=><button key={report.id} className={selectedId===report.id?'active':''} aria-pressed={selectedId===report.id} onClick={()=>{setSelectedId(report.id);setMessage('')}}><span>{report.kind} / {report.id}</span><b>{report.title}</b><small>{report.updated}</small></button>)}</div><div className="report-group"><h3>Issued</h3>{demoReports.filter(report=>report.status==='Issued').map(report=><button key={report.id} className={selectedId===report.id?'active':''} aria-pressed={selectedId===report.id} onClick={()=>{setSelectedId(report.id);setMessage('')}}><span>{report.kind} / {report.id}</span><b>{report.title}</b><small>{report.updated}</small></button>)}</div></aside>
  <main className="report-preview-area"><div className="report-toolbar"><span>Original layout · Version {version}</span><div><button onClick={()=>window.print()}><Printer/> Print</button>{selected.id==='P-024'?<a href="/demo/BUI-1042-issue-package.pdf" target="_blank" rel="noreferrer"><Download/> PDF</a>:<button disabled title="This demo artifact is not bundled"><Download/> PDF</button>}<button onClick={shareReport}><Mail/> Share</button></div></div>{selected.id==='P-024'?<article className="report-sheet">
    <header className="report-brand"><div><img src="/brand/buili-logo.png" alt="BUILI"/><span>VERIFIED FIELD ACTION</span></div><p>NORTHSTAR BUILDERS<br/><b>COOPER RESIDENCE RENOVATION</b></p></header>
    <div className="report-title-block"><span>PUNCH ITEM · P-024</span><h1>Garage GFCI receptacle below required elevation</h1><p>Prepared from field issue BUI-1042 · July 12, 2026</p></div>
    <div className="report-meta"><div><span>Location</span><b>Garage · East wall · Entry door</b></div><div><span>Responsible trade</span><b>Delta Electrical</b></div><div><span>Due before</span><b>Wall close-in · July 14</b></div><div><span>Status</span><StatusPill tone="green">Ready for review</StatusPill></div></div>
    <section className="report-finding"><h2>Verified finding</h2><p>The installed GFCI receptacle centerline measures <strong>12 in. above finished floor</strong>. E1.1 Electrical Note 3 requires garage receptacles at a minimum of <strong>18 in. above finished floor</strong>.</p><div><span>Observed<strong>12 in. AFF</strong></span><i>→</i><span>Required<strong>18 in. AFF min.</strong></span><em>−6 in.</em></div></section>
    <section className="report-action"><h2>Required action</h2><p>Raise the garage east-wall GFCI receptacle box to a minimum centerline elevation of 18 in. AFF before wall close-in. Upload one completion photograph with a visible measurement for verification.</p></section>
    <section className="report-evidence-strip"><h2>Field evidence</h2><div><figure><img src="/demo/garage-east-wall-context-thumb.webp" alt="Garage east wall context"/><figcaption>01 · Room context</figcaption></figure><figure><img src="/demo/receptacle-rough-in-detail-thumb.webp" alt="GFCI rough-in detail"/><figcaption>02 · Installation detail</figcaption></figure><figure><img src="/demo/box-elevation-measurement-thumb.webp" alt="Box elevation measurement"/><figcaption>03 · Dimension proof</figcaption></figure></div></section>
    <section className="report-source"><FileText/><div><span>CONTROLLING SOURCE</span><b>E1.1 · REV 03 · ELECTRICAL NOTE 3</b><p>“Garage receptacles: mount at 18 in. AFF minimum unless noted otherwise.”</p></div><Check/></section>
    <footer className="report-footer"><span>{issued?'Approved in this demo session':'Source-cited draft · Not issued until approved'}</span><span>BUILI / P-024 / V{version}</span></footer>
  </article>:<article className="report-sheet report-sheet--alternate"><header className="report-brand"><div><img src="/brand/buili-logo.png" alt="BUILI"/><span>PROJECT REPORT</span></div><p>NORTHSTAR BUILDERS<br/><b>COOPER RESIDENCE RENOVATION</b></p></header><div className="report-title-block"><span>{selected.kind.toUpperCase()} · {selected.id}</span><h1>{selected.title}</h1><p>{selected.updated}</p></div><section className="report-action"><h2>Demo preview boundary</h2><p>This report is included to demonstrate report navigation and status. Only P-024 includes a bundled source-cited artifact; no external export is simulated for this item.</p></section><footer className="report-footer"><span>{selected.status}</span><span>BUILI / {selected.id}</span></footer></article>}</main>
  <aside className="report-review"><div className="panel-title"><b>Review & issue</b><button disabled title="Additional review actions are unavailable in the demo" aria-label="Additional review actions"><MoreHorizontal/></button></div><div className="review-scroll"><section><h3>Approval</h3><StatusPill tone={selected.status==='Issued'||issued?'blue':'green'}>{selected.status==='Issued'||issued?'Issued':'Evidence sufficient'}</StatusPill><p>{selected.id==='P-024'?'Sources, location, measurement, and recommended action are complete.':'This item is read-only in the representative demo.'}</p></section><section><h3>Prepared by</h3><div className="review-person"><span>JC</span><p><b>Jordan Cho</b><small>Project Manager</small></p></div></section><section><h3>Revision note</h3><textarea value={revisionNote} onChange={event=>setRevisionNote(event.target.value)} maxLength={500} disabled={selected.id!=='P-024'}/></section><section><h3>Destinations</h3><label><input type="checkbox" defaultChecked disabled={selected.id!=='P-024'}/> Project issue log</label><label><input type="checkbox" defaultChecked disabled={selected.id!=='P-024'}/> Delta Electrical</label><label title="Configure Procore in organization settings"><input type="checkbox" disabled/> Procore export · not configured</label></section>{message&&<p className="inline-success" role="status">{message}</p>}</div><div className="review-actions"><button className="button button--secondary" onClick={saveVersion} disabled={selected.id!=='P-024'}><Save/> Save version</button><button className="button button--primary" onClick={()=>{setIssued(true);setMessage('Demo report approved for the project issue log. No external system was contacted.')}} disabled={selected.id!=='P-024'||issued}><Send/> {issued?'Approved':'Approve & issue'}</button></div></aside>
 </div>}

type LiveReport={id:string;kind:string;status:string;version:number;title:string;created_at:string};
function LiveReports({projectId}:{projectId:string}){const[reports,setReports]=useState<LiveReport[]>([]);const[error,setError]=useState('');useEffect(()=>{if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<LiveReport[]>(`/projects/${projectId}/reports`).then(rows=>{if(active)setReports(rows)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Reports could not be loaded.')});return()=>{active=false}},[projectId]);async function openReport(id:string){try{const result=await api.get<{report:LiveReport;download_url:string}>(`/reports/${id}`);window.open(result.download_url,'_blank','noopener,noreferrer')}catch(cause){setError(cause instanceof Error?cause.message:'Report could not be opened.')}}return <div className="page-pad"><PageHeader title="Reports" description="Versioned, source-cited project outputs generated from approved issues."/>{error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Report</th><th>Kind</th><th>Status</th><th>Version</th><th>Created</th><th/></tr></thead><tbody>{reports.map(report=><tr key={report.id}><td className="cell-title"><b>{report.title}</b><small className="cell-id">{report.id}</small></td><td>{report.kind.replaceAll('_',' ')}</td><td><StatusPill tone={report.status==='approved'?'green':'neutral'}>{report.status}</StatusPill></td><td className="cell-id">v{report.version}</td><td className="cell-muted">{new Date(report.created_at).toLocaleString()}</td><td><button className="button button--secondary button--small" onClick={()=>openReport(report.id)}><Download/> Open</button></td></tr>)}</tbody></table></div>{reports.length===0&&!error&&<div className="live-placeholder"><FileText/><p><b>No reports have been generated.</b><span>Approve an issue, then generate an RFI, punch, change event, or evidence package.</span></p></div>}</div>}
