'use client';

import { Check, Download, FileText, Mail, MoreHorizontal, Printer, Save, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import { StatusPill } from '@/components/status-pill';
import { useWorkspace } from '@/components/demo-mode';
import { PageHeader } from '@/components/page-header';
import { api } from '@/lib/api';

type DemoReport = {
  id:string; kind:string; title:string; status:string; updated:string; pdf:string; docx:string;
  location:string; source:string; sourceText:string; facts:Array<[string,string]>; sections:Array<[string,string]>; images?:boolean;
};

const demoReports:DemoReport[]=[
  {id:'P-024',kind:'Punch item',title:'Raise garage GFCI rough-in before wall close-in',status:'Ready for review',updated:'Updated 4 min ago',pdf:'/demo/P-024-punch-item.pdf',docx:'/demo/P-024-punch-item.docx',location:'Garage / East wall / Entry door',source:'E1.1 / Rev 03 / Note 3',sourceText:'Garage receptacle centerline shall be minimum 18 inches above finished floor.',facts:[['Responsible trade','Delta Electrical'],['Punch manager','Jordan Cho'],['Final approver','Jordan Cho'],['Due date','Jul 14, 2026']],sections:[['Deficiency','GFCI box centerline measures 12 inches above finished floor.'],['Required correction','Relocate the box to at least 18 inches AFF before gypsum board installation.'],['Completion proof','Upload a full-wall photo and a readable tape measurement from finished floor to box centerline.']],images:true},
  {id:'RFI-018',kind:'RFI draft',title:'Office partition dimension conflict at grid C',status:'Draft',updated:'Updated 31 min ago',pdf:'/demo/RFI-018-partition-dimension.pdf',docx:'/demo/RFI-018-partition-dimension.docx',location:'Office / Grid C',source:'A1.1 / Rev 03',sourceText:'The office partition is dimensioned from the west exterior wall face.',facts:[['Ball in court','Studio North Architects'],['Due date','Jul 16, 2026'],['Cost impact','Unknown - layout hold'],['Schedule impact','2 working days']],sections:[['Existing condition','The floor plan and enlarged detail use different dimension origins.'],['Document conflict','The references produce a 76 mm difference in partition location.'],['Question','Please confirm the controlling reference and approved offset from grid C.'],['Suggested answer - for review','Use the grid-based detail dimension, subject to architect confirmation.']]},
  {id:'RFI-017',kind:'RFI',title:'Return-air route at hall opening',status:'Issued',updated:'Issued yesterday',pdf:'/demo/RFI-017-hvac-route.pdf',docx:'/demo/RFI-017-hvac-route.docx',location:'Hall ceiling / Opening H-2',source:'M1.1 / Rev 03',sourceText:'Return-air branch RA-2 passes through the hall coordination zone.',facts:[['Ball in court','Vector MEP'],['Due date','Jul 14, 2026'],['Cost impact','TBD'],['Schedule impact','Hall framing hold']],sections:[['Existing condition','Return-air route RA-2 crosses the framed opening clearance zone.'],['Question','Provide the approved elevation and route at opening H-2, or confirm the alternate laundry-ceiling route.'],['Official response','Pending.']]},
  {id:'CE-007',kind:'Change event',title:'Existing footing below new laundry wall',status:'Issued',updated:'Issued Jul 10',pdf:'/demo/CE-007-existing-footing.pdf',docx:'/demo/CE-007-existing-footing.docx',location:'Laundry / South wall',source:'A1.1 / Rev 03',sourceText:'The original plan indicates a clear trench path through the south wall zone.',facts:[['Origin','Field observation BUI-1034'],['Reason','Unforeseen condition'],['Scope','TBD - outside documented condition'],['ROM','$3,850']],sections:[['Changed condition','Selective demolition exposed an undocumented concrete footing within the plumbing trench alignment.'],['Basis of change','The concealed footing requires a revised route or engineered penetration and was not shown in the bid documents.'],['Schedule position','One working day trench hold; no critical-path impact if direction is received by Jul 15.']]},
  {id:'DR-2026-07-12',kind:'Daily report',title:'Daily field report - electrical rough-in',status:'Complete',updated:'Completed Jul 12',pdf:'/demo/DR-2026-07-12-daily-report.pdf',docx:'/demo/DR-2026-07-12-daily-report.docx',location:'Ground floor / All active areas',source:'Field record / Jul 12',sourceText:'Three companies, nine workers, 72 total labor hours; no safety incident or weather delay.',facts:[['Report date','Jul 12, 2026'],['Weather','Clear / dry'],['Workers','9'],['Labor hours','72']],sections:[['Work completed','Electrical branch rough-in at garage and living areas; laundry supply rough-in; office partition layout verification.'],['Safety and inspections','Pre-task plan completed. No incidents, near misses, or failed inspections.'],['Open observation','Garage GFCI elevation was routed to punch before wall close-in.']],images:true},
  {id:'BUI-1042',kind:'Issue package',title:'Garage GFCI receptacle below required elevation',status:'Ready for review',updated:'Updated 4 min ago',pdf:'/demo/BUI-1042-issue-package.pdf',docx:'/demo/BUI-1042-issue-package.docx',location:'Garage / East wall / Entry door',source:'E1.1 / Rev 03 / Note 3',sourceText:'Garage receptacle centerline shall be minimum 18 inches above finished floor.',facts:[['Priority','High'],['Classification','Unapproved deviation'],['Evidence','Sufficient'],['Route','Field correction punch']],sections:[['Observed condition','GFCI box centerline measures 12 inches above finished floor.'],['Required condition','Electrical Note 3 requires a minimum 18 inches AFF.'],['Verified difference','Installed centerline is 6 inches below the approved requirement.']],images:true},
];

export default function ReportsPage(){
  const{demo,projectId}=useWorkspace();
  const[selectedId,setSelectedId]=useState('P-024');
  const[version,setVersion]=useState(3);
  const[approved,setApproved]=useState<string[]>([]);
  const[message,setMessage]=useState('');
  const[revisionNote,setRevisionNote]=useState('Verified against linked field evidence and the controlling revision.');
  if(!demo)return <LiveReports projectId={projectId}/>;
  const selected=demoReports.find(report=>report.id===selectedId)||demoReports[0];
  const isIssued=selected.status==='Issued'||selected.status==='Complete'||approved.includes(selected.id);
  async function shareReport(){
    setMessage('');
    const url=`${window.location.origin}${selected.pdf}`;
    try{if(navigator.share)await navigator.share({title:`${selected.kind} ${selected.id}`,text:selected.title,url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);setMessage('Report link copied to clipboard.')}else setMessage('Sharing is not supported in this browser.')}catch(cause){if((cause as DOMException)?.name!=='AbortError')setMessage('The report could not be shared.')}
  }
  function saveVersion(){setVersion(value=>value+1);setMessage(`Demo version ${version+1} saved for this browser session.`)}
  return <div className="reports-workspace">
    <aside className="report-list"><div className="panel-title"><b>Reports</b><button disabled title="Additional report actions are unavailable in the demo" aria-label="Additional report actions"><MoreHorizontal/></button></div><div className="report-group"><h3>Ready for review</h3>{demoReports.filter(report=>!['Issued','Complete'].includes(report.status)).map(report=><button key={report.id} className={selectedId===report.id?'active':''} aria-pressed={selectedId===report.id} onClick={()=>{setSelectedId(report.id);setMessage('')}}><span>{report.kind} / {report.id}</span><b>{report.title}</b><small>{report.updated}</small></button>)}</div><div className="report-group"><h3>Issued & complete</h3>{demoReports.filter(report=>['Issued','Complete'].includes(report.status)).map(report=><button key={report.id} className={selectedId===report.id?'active':''} aria-pressed={selectedId===report.id} onClick={()=>{setSelectedId(report.id);setMessage('')}}><span>{report.kind} / {report.id}</span><b>{report.title}</b><small>{report.updated}</small></button>)}</div></aside>
    <main className="report-preview-area"><div className="report-toolbar"><span>BUILI operational layout · Version {version}</span><div><button onClick={()=>window.print()}><Printer/> Print</button><a href={selected.pdf} target="_blank" rel="noreferrer"><Download/> PDF</a><a href={selected.docx} target="_blank" rel="noreferrer"><FileText/> DOCX</a><button onClick={shareReport}><Mail/> Share</button></div></div><article className="report-sheet"><header className="report-brand"><div><img src="/brand/buili-logo.png" alt="BUILI"/><span>SOURCE-CITED PROJECT RECORD</span></div><p>NORTHSTAR BUILDERS<br/><b>COOPER RESIDENCE RENOVATION</b></p></header><div className="report-title-block"><span>{selected.kind.toUpperCase()} · {selected.id}</span><h1>{selected.title}</h1><p>{selected.location} · July 2026</p></div><div className="report-meta">{selected.facts.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div>{selected.sections.map(([heading,body],index)=><section key={heading} className={index===1?'report-action':'report-finding'}><h2>{heading}</h2><p>{body}</p></section>)}{selected.images&&<section className="report-evidence-strip"><h2>Linked field evidence</h2><div><figure><img src="/demo/garage-east-wall-context-thumb.webp" alt="Garage east wall context"/><figcaption>01 · Room context</figcaption></figure><figure><img src="/demo/receptacle-rough-in-detail-thumb.webp" alt="Installation detail"/><figcaption>02 · Installation detail</figcaption></figure><figure><img src="/demo/box-elevation-measurement-thumb.webp" alt="Dimension proof"/><figcaption>03 · Dimension proof</figcaption></figure></div></section>}<section className="report-source"><FileText/><div><span>CONTROLLING RECORD</span><b>{selected.source}</b><p>{selected.sourceText}</p></div><Check/></section><footer className="report-footer"><span>{isIssued?'Approved or complete record':'Source-cited draft · review required before issue'}</span><span>BUILI / {selected.id} / V{version}</span></footer></article></main>
    <aside className="report-review"><div className="panel-title"><b>Review & issue</b><button disabled title="Additional review actions are unavailable in the demo" aria-label="Additional review actions"><MoreHorizontal/></button></div><div className="review-scroll"><section><h3>Control</h3><StatusPill tone={isIssued?'blue':'green'}>{isIssued?'Issued / complete':'Reviewable draft'}</StatusPill><p>Required operational fields, exact source revision, and export artifacts are bundled for this record.</p></section><section><h3>Prepared by</h3><div className="review-person"><span>JC</span><p><b>Jordan Cho</b><small>Project Manager</small></p></div></section><section><h3>Revision note</h3><textarea value={revisionNote} onChange={event=>setRevisionNote(event.target.value)} maxLength={500}/></section><section><h3>Destinations</h3><label><input type="checkbox" defaultChecked/> Project record</label><label><input type="checkbox" defaultChecked/> Responsible team</label><label title="Configure Procore in organization settings"><input type="checkbox" disabled/> Procore export · not configured</label></section>{message&&<p className="inline-success" role="status">{message}</p>}</div><div className="review-actions"><button className="button button--secondary" onClick={saveVersion}><Save/> Save version</button><button className="button button--primary" onClick={()=>{setApproved(ids=>[...ids,selected.id]);setMessage('Demo report approved for the project record. No external system was contacted.')}} disabled={isIssued}><Send/> {isIssued?'Approved':'Approve & issue'}</button></div></aside>
  </div>;
}

type LiveReport={id:string;kind:string;status:string;version:number;title:string;created_at:string};
function LiveReports({projectId}:{projectId:string}){const[reports,setReports]=useState<LiveReport[]>([]);const[error,setError]=useState('');useEffect(()=>{if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<LiveReport[]>(`/projects/${projectId}/reports`).then(rows=>{if(active)setReports(rows)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Reports could not be loaded.')});return()=>{active=false}},[projectId]);async function openReport(id:string){try{const result=await api.get<{report:LiveReport;download_url:string}>(`/reports/${id}`);window.open(result.download_url,'_blank','noopener,noreferrer')}catch(cause){setError(cause instanceof Error?cause.message:'Report could not be opened.')}}return <div className="page-pad"><PageHeader title="Reports" description="Versioned, source-cited project outputs generated from approved issues."/>{error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Report</th><th>Kind</th><th>Status</th><th>Version</th><th>Created</th><th/></tr></thead><tbody>{reports.map(report=><tr key={report.id}><td className="cell-title"><b>{report.title}</b><small className="cell-id">{report.id}</small></td><td>{report.kind.replaceAll('_',' ')}</td><td><StatusPill tone={report.status==='approved'?'green':'neutral'}>{report.status}</StatusPill></td><td className="cell-id">v{report.version}</td><td className="cell-muted">{new Date(report.created_at).toLocaleString()}</td><td><button className="button button--secondary button--small" onClick={()=>openReport(report.id)}><Download/> Open</button></td></tr>)}</tbody></table></div>{reports.length===0&&!error&&<div className="live-placeholder"><FileText/><p><b>No reports have been generated.</b><span>Approve an issue, then generate an RFI, punch, change event, daily report, or evidence package.</span></p></div>}</div>}
