'use client';
import { ChevronDown, Download, FileCheck2, FileText, KeyRound, LogIn, Search, ShieldCheck, UserPlus } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { api } from '@/lib/api';

const demoLog=[
 ['4:27 PM','Jordan Cho','ISSUE_READY_FOR_REVIEW','BUI-1042','Status: TRIAGE → READY_FOR_REVIEW','issue'],
 ['4:20 PM','BUILI Analysis','SOURCE_VERIFIED','E1.1 Rev 03','Current controlling source selected','source'],
 ['4:19 PM','BUILI Analysis','EVIDENCE_ANALYZED','ev_set_1042','4 assets · sufficiency 96/100','analysis'],
 ['4:18 PM','Mike Alvarez','EVIDENCE_CREATED','box-elevation-measurement.png','SHA-256 verified · 12 in. AFF','file'],
 ['4:17 PM','Mike Alvarez','ISSUE_CREATED','BUI-1042','Garage east wall · Entry door','issue'],
 ['3:08 PM','Jordan Cho','DOCUMENT_APPROVED','E1.1 Rev 03','Marked current project requirement','source'],
 ['9:12 AM','Daniel Ruiz','USER_LOGIN','web_session_91F','MFA verified · San Jose, CA','login']
];
export default function AuditPage(){const{demo,projectId}=useWorkspace();const[log,setLog]=useState<string[][]>(demo?demoLog:[]);const[error,setError]=useState('');useEffect(()=>{if(demo){setLog(demoLog);return}if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<Array<{id:string;action:string;resource_type:string;resource_id:string;actor_user_id:string|null;details:Record<string,unknown>;request_id:string;created_at:string}>>(`/projects/${projectId}/audit?limit=50&offset=0`).then(rows=>{if(active)setLog(rows.map(row=>[new Date(row.created_at).toLocaleString(),row.actor_user_id?.slice(0,8)||'System',row.action,row.resource_id,detailSummary(row.details),row.resource_type]))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Audit history could not be loaded.')});return()=>{active=false}},[demo,projectId]);return <div className="page-pad"><PageHeader title="Audit trail" description="Immutable project history for source changes, AI analysis, human review, access, and formal exports." actions={<button className="button button--secondary"><Download size={14}/> Export audit log</button>}/><div className="audit-assurance"><ShieldCheck/><div><b>Project audit history is protected</b><p>Events are append-only. Each export includes source identifiers, actor, timestamp, and request ID.</p></div><span>Retention / organization policy</span></div><div className="filter-row"><div className="table-search"><Search/><input placeholder="Search event or object"/></div><button className="filter-button">All actors <ChevronDown/></button><button className="filter-button">All event types <ChevronDown/></button><button className="filter-button">Last 30 days <ChevronDown/></button></div>{error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><div className="audit-log"><div className="audit-head"><span>Time</span><span>Actor</span><span>Event</span><span>Object</span><span>Change</span></div>{log.map((item,index)=><div className="audit-row" key={`${item[0]}-${index}`}><span className="audit-time">{item[0]}</span><span>{item[1]}</span><span className="audit-event"><AuditIcon type={item[5]}/><b>{item[2]}</b></span><span className="cell-id">{item[3]}</span><span className="cell-muted">{item[4]}</span></div>)}</div></div></div>}
function AuditIcon({type}:{type:string}){if(type==='login')return <LogIn/>;if(type==='file')return <FileText/>;if(type==='analysis')return <FileCheck2/>;if(type==='source')return <KeyRound/>;return <ShieldCheck/>}
function detailSummary(details:Record<string,unknown>){const entries=Object.entries(details||{}).slice(0,3);return entries.length?entries.map(([key,value])=>`${key}: ${String(value)}`).join(' / '):'No field changes recorded'}
