'use client';
import Link from 'next/link';
import { ArrowRight, Building2, ChevronDown, ListFilter, MapPin, Plus, Search } from 'lucide-react';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { PageHeader } from '@/components/page-header';
import { useWorkspace } from '@/components/demo-mode';
import { projects as demoProjects } from '@/lib/demo-data';
import type { Project } from '@/lib/types';
import { api } from '@/lib/api';

export default function ProjectsPage() {
  const {demo,organizationId}=useWorkspace(); const router=useRouter(); const [projects,setProjects]=useState<Project[]>(demo?demoProjects:[]); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const[phase,setPhase]=useState('all'); const[sort,setSort]=useState('updated'); const[creating,setCreating]=useState(false); const[showCreate,setShowCreate]=useState(false);
  useEffect(()=>{if(demo){setProjects(demoProjects);return}let active=true;api.get<Array<{id:string;name:string;code:string;address:string;status:string;metadata_json?:Record<string,unknown>;created_at:string;updated_at:string}>>('/projects').then(rows=>{if(active)setProjects(rows.map(row=>({id:row.id,name:row.name,code:row.code,location:row.address,phase:row.status,progress:Number(row.metadata_json?.progress||0),openIssues:Number(row.metadata_json?.open_issues||0),evidenceCoverage:Number(row.metadata_json?.evidence_coverage||0),updatedAt:new Date(row.updated_at||row.created_at).toLocaleDateString()})))}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Projects could not be loaded.')});return()=>{active=false}},[demo]);
  const phases=useMemo(()=>Array.from(new Set(projects.map(project=>project.phase))).sort(),[projects]);
  const visibleProjects=useMemo(()=>projects.filter(project=>{const needle=query.trim().toLowerCase();return(!needle||`${project.name} ${project.code} ${project.location}`.toLowerCase().includes(needle))&&(phase==='all'||project.phase===phase)}).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):b.updatedAt.localeCompare(a.updatedAt)),[phase,projects,query,sort]);
  async function createProject(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!organizationId){setError('Create or select an organization before adding a project.');return}setCreating(true);setError('');const data=new FormData(event.currentTarget);try{const created=await api.post<{id:string}>('/projects',{organization_id:organizationId,name:String(data.get('name')),code:String(data.get('code')),project_type:String(data.get('project_type')),address:String(data.get('address')),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Los_Angeles',units:'imperial',metadata_json:{}});localStorage.setItem('buili-current-project',created.id);router.push(`/app?project=${encodeURIComponent(created.id)}`)}catch(cause){setError(cause instanceof Error?cause.message:'Project could not be created.')}finally{setCreating(false)}}
  return <div className="page-pad"><PageHeader title="Projects" description="Manage active work, project context, members, and integrations." actions={demo?<Link className="button button--primary" href="/signup"><Plus size={14}/> Create workspace</Link>:<button className="button button--primary" onClick={()=>setShowCreate(true)}><Plus size={14}/> New project</button>}/>
    <div className="filter-row"><div className="table-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search projects" aria-label="Search projects"/></div><select className="filter-button" value={phase} onChange={event=>setPhase(event.target.value)} aria-label="Filter by phase"><option value="all">All phases</option>{phases.map(item=><option key={item}>{item}</option>)}</select><span className="filter-spacer"/><select className="filter-button" value={sort} onChange={event=>setSort(event.target.value)} aria-label="Sort projects"><option value="updated">Recently updated</option><option value="name">Project name</option></select></div>
    <div className="project-list-head"><span>Project</span><span>Phase</span><span>Progress</span><span>Open issues</span><span>Evidence</span><span>Updated</span></div>
    {error&&<p className="inline-error" role="alert">{error}</p>}<div className="project-list">{visibleProjects.map(project=><Link key={project.id} href={`/app?project=${encodeURIComponent(project.id)}${demo?'&demo=1':''}`} className="project-row"><span className="project-icon"><Building2/></span><div className="project-name"><b>{project.name}</b><small><MapPin/> {project.location||'Location not set'} / {project.code}</small></div><span className="project-phase">{project.phase}</span><span className="project-progress"><i><b style={{width:`${project.progress}%`}}/></i><em>{project.progress}%</em></span><strong>{String(project.openIssues).padStart(2,'0')}</strong><strong>{project.evidenceCoverage}%</strong><span className="cell-muted">{project.updatedAt}</span><ArrowRight/></Link>)}{visibleProjects.length===0&&<div className="live-placeholder"><Search/><p><b>No matching projects.</b><span>Clear the search or choose another phase.</span></p></div>}</div>
    <section className="archived-prompt"><div><h2>Completed projects</h2><p>Retain your source record, issued reports, approvals, and audit history after closeout.</p></div><button className="button button--secondary" onClick={()=>setPhase('archived')}>View archive</button></section>
    {showCreate&&<div className="product-dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setShowCreate(false)}}><dialog className="product-dialog" open aria-modal="true" aria-labelledby="new-project-title" onKeyDown={event=>{if(event.key==='Escape')setShowCreate(false)}}><form onSubmit={createProject}><header><div><span>Project setup</span><h2 id="new-project-title">Create a project</h2></div><button type="button" className="icon-button" onClick={()=>setShowCreate(false)} aria-label="Close project form">×</button></header><div className="settings-form"><label>Project name<input name="name" minLength={2} maxLength={240} required autoFocus/></label><label>Project code<input name="code" maxLength={80} required/></label><label>Project type<select name="project_type" defaultValue="renovation"><option value="renovation">Renovation</option><option value="tenant_improvement">Tenant improvement</option><option value="new_construction">New construction</option><option value="fit_out">Fit-out</option></select></label><label>Address<input name="address" autoComplete="street-address"/></label></div><footer><button type="button" className="button button--secondary" onClick={()=>setShowCreate(false)}>Cancel</button><button className="button button--primary" disabled={creating}>{creating?'Creating...':'Create project'}</button></footer></form></dialog></div>}
  </div>;
}
