'use client';

import { useRouter } from 'next/navigation';
import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, Check, CheckCircle2, ChevronDown, Film, ImagePlus, LoaderCircle, MapPin, Mic, Pause, Plus, Ruler, ShieldCheck, Sparkles, Square, X } from 'lucide-react';
import { api } from '@/lib/api';
import { uploadProjectFile } from '@/lib/uploads';
import { useWorkspace } from './demo-mode';

type CaptureAsset = { file: File; url: string; kind: 'photo'|'video'|'audio' };
type CaptureValidationInput = { room:string; position:string; assetCount:number; demoEvidence:boolean; note:string; measurement:string };
const MAX_CAPTURE_ASSETS=12;
const MAX_IMAGE_BYTES=25*1024*1024;
const MAX_VIDEO_BYTES=250*1024*1024;

export function captureValidationMessage(targetStep:number,input:CaptureValidationInput){if(targetStep===1&&(!input.room.trim()||!input.position.trim()))return 'Select a space and describe the exact field position.';if(targetStep===2&&input.assetCount===0&&!input.demoEvidence)return 'Add at least one photo, video, or voice note.';if(targetStep===3&&!input.note.trim())return 'Describe the observed field condition.';if(targetStep===3&&input.measurement.trim()&&(!Number.isFinite(Number(input.measurement))||Number(input.measurement)<=0))return 'Enter a positive measurement or leave the measurement empty.';return ''}
export function captureFileError(files:File[],currentCount:number){if(currentCount+files.length>MAX_CAPTURE_ASSETS)return `Add no more than ${MAX_CAPTURE_ASSETS} evidence assets to one observation.`;for(const file of files){if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return `${file.name} is not a supported photo or video.`;const limit=file.type.startsWith('video/')?MAX_VIDEO_BYTES:MAX_IMAGE_BYTES;if(file.size>limit)return `${file.name} exceeds the ${Math.round(limit/1024/1024)} MB limit.`}return ''}

export function CaptureFlow() {
  const router=useRouter(); const {demo,organizationId,projectId,projectName}=useWorkspace(); const [step,setStep]=useState(1); const [assets,setAssets]=useState<CaptureAsset[]>([]); const [room,setRoom]=useState(''); const [position,setPosition]=useState(''); const [note,setNote]=useState(''); const [measurement,setMeasurement]=useState(''); const [recording,setRecording]=useState(false); const [saving,setSaving]=useState(false); const [progress,setProgress]=useState(0); const [saveError,setSaveError]=useState(''); const [stepError,setStepError]=useState(''); const [demoEvidenceSelected,setDemoEvidenceSelected]=useState(false); const recorder=useRef<MediaRecorder|null>(null); const activeStream=useRef<MediaStream|null>(null); const chunks=useRef<Blob[]>([]); const objectUrls=useRef(new Set<string>());
  useEffect(()=>{if(demo){setRoom('Garage');setPosition('East wall / Entry door');setNote('GFCI box appears lower than the minimum shown in Electrical Note 3.');setMeasurement('12');setDemoEvidenceSelected(true)}},[demo]);
  useEffect(()=>()=>{if(recorder.current?.state==='recording')recorder.current.stop();activeStream.current?.getTracks().forEach(track=>track.stop());objectUrls.current.forEach(url=>URL.revokeObjectURL(url));objectUrls.current.clear()},[]);
  function addFiles(event:ChangeEvent<HTMLInputElement>){const files=[...(event.target.files||[])];event.target.value='';const fileError=captureFileError(files,assets.length);if(fileError){setStepError(fileError);return}const added=files.map(file=>{const url=URL.createObjectURL(file);objectUrls.current.add(url);return{file,url,kind:file.type.startsWith('video/')?'video' as const:'photo' as const}});setAssets(current=>[...current,...added]);setStepError('')}
  function removeAsset(index:number){setAssets(items=>{const removed=items[index];if(removed){URL.revokeObjectURL(removed.url);objectUrls.current.delete(removed.url)}return items.filter((_,itemIndex)=>itemIndex!==index)})}
  async function toggleRecording(){ if(recording){recorder.current?.stop();setRecording(false);return} if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setStepError('Voice recording is not supported in this browser. Add an audio file from your device instead.');return}if(assets.length>=MAX_CAPTURE_ASSETS){setStepError(`Add no more than ${MAX_CAPTURE_ASSETS} evidence assets to one observation.`);return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});activeStream.current=stream;const instance=new MediaRecorder(stream);chunks.current=[];instance.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};instance.onstop=()=>{const blob=new Blob(chunks.current,{type:instance.mimeType});if(blob.size){const file=new File([blob],`field-note-${Date.now()}.webm`,{type:blob.type});const url=URL.createObjectURL(file);objectUrls.current.add(url);setAssets(current=>[...current,{file,url,kind:'audio'}]);setStepError('')}stream.getTracks().forEach(track=>track.stop());activeStream.current=null};instance.start();recorder.current=instance;setRecording(true);setStepError('')}catch{setStepError('Microphone access is required to record a field note. Check browser permissions or add a file instead.')}}
  function validationMessage(targetStep:number){return captureValidationMessage(targetStep,{room,position,assetCount:assets.length,demoEvidence:demo&&demoEvidenceSelected,note,measurement})}
  function continueFlow(){const message=validationMessage(step);if(message){setStepError(message);return}setStepError('');setStep(step+1)}
  async function save(){for(const candidate of [1,2,3]){const message=validationMessage(candidate);if(message){setStep(candidate);setStepError(message);return}}setSaving(true);setSaveError('');if(demo){setProgress(100);setTimeout(()=>router.push('/app/issues/BUI-1042?demo=1'),350);return}try{if(!organizationId||!projectId)throw new Error('Select a project before capturing evidence.');const evidenceIds:string[]=[];for(let index=0;index<assets.length;index++){const asset=assets[index];const upload=await uploadProjectFile(organizationId,projectId,asset.file,value=>setProgress(Math.round((index*100+value)/Math.max(assets.length,1))));const evidence=await api.post<{id:string}>(`/projects/${projectId}/evidence`,{upload_id:upload.id,kind:asset.kind==='audio'?'voice_note':asset.kind,title:asset.file.name,description:note,captured_at:new Date().toISOString(),location_json:{space:room,position,confidence:'USER_CONFIRMED'},metadata_json:{capture_source:'BUILI_WEB'},transcript:'',analyze:false});evidenceIds.push(evidence.id)}if(measurement.trim()){const measurementEvidence=await api.post<{id:string}>(`/projects/${projectId}/evidence`,{kind:'measurement',title:'Field elevation measurement',description:`Measured ${measurement} in. AFF`,captured_at:new Date().toISOString(),location_json:{space:room,position,confidence:'USER_CONFIRMED'},metadata_json:{measurement:{type:'ELEVATION_AFF',value:Number(measurement),unit:'inch',reference:'AFF'}},transcript:'',analyze:false});evidenceIds.push(measurementEvidence.id)}const measuredCondition=measurement.trim()?` Field team measured ${measurement} in. AFF.`:'';const issue=await api.post<{id:string}>(`/projects/${projectId}/issues`,{title:'Field observation requires review',description:note,issue_type:'field_deviation',priority:'normal',observed_condition:`${note}${measuredCondition}`,expected_condition:'',difference:'',classification:'insufficient_evidence',recommended_action:'additional_evidence_required',location_json:{space:room,position},evidence_ids:evidenceIds,revision_ids:[]});router.push(`/app/issues/${issue.id}`)}catch(cause){setSaveError(cause instanceof Error?cause.message:'The observation could not be saved.')}finally{setSaving(false)}}

  return <div className="capture-page"><header className="capture-header"><button type="button" onClick={()=>step>1?setStep(step-1):router.back()} aria-label="Go back"><ArrowLeft/></button><div><span>Field capture</span><b>{step} of 4</b></div><button type="button" onClick={()=>router.push('/app')} aria-label="Close"><X/></button></header><div className="capture-progress" role="progressbar" aria-label="Capture progress" aria-valuemin={0} aria-valuemax={4} aria-valuenow={step}><i style={{width:`${step*25}%`}}/></div>
    <main className="capture-content">
      {step===1&&<section className="capture-step"><p className="capture-eyebrow">Location</p><h1>Where are you?</h1><p>Confirm the location now so every photo and note stays spatially grounded.</p><button className="location-project" onClick={()=>router.push('/app/projects')}><span>PR</span><div><small>Current project</small><b>{projectName||'Select a project'}</b></div><ChevronDown/></button><label className="capture-select"><span>Space</span><select value={room} onChange={e=>{setRoom(e.target.value);setStepError('')}} required><option value="">Select space</option><option>Garage</option><option>Entry</option><option>Kitchen</option><option>Living room</option></select></label><label className="capture-select"><span>Position</span><input value={position} onChange={e=>{setPosition(e.target.value);setStepError('')}} placeholder="Wall, grid, or nearby object"/></label><div className="capture-map"><svg viewBox="0 0 360 220"><path d="M30 30h300v160H30zM30 115h100V30m0 85h100V30m0 85h100M130 115v75m100-75v75"/><g transform="translate(124 75)"><circle r="18"/><circle r="5"/></g><text x="48" y="56">SPACE</text><text x="150" y="56">ZONE</text><text x="248" y="56">ROOM</text></svg><span><MapPin/> {room?'Location confirmed by you':'Select a space above'}</span></div></section>}
      {step===2&&<section className="capture-step"><p className="capture-eyebrow">Evidence</p><h1>Show what you found.</h1><p>Capture a wide view, a close detail, and a visible measurement when possible.</p>{demo&&demoEvidenceSelected&&assets.length===0&&<div className="demo-evidence-ready"><CheckCircle2/><div><b>Representative evidence set ready</b><span>3 field photos and 1 verified voice note are attached to this demo observation.</span></div></div>}<div className="capture-actions"><label className="capture-action capture-action--primary"><input hidden type="file" accept="image/*" capture="environment" multiple onChange={addFiles}/><Camera/><span><b>Take photos</b><small>Use the rear camera</small></span><ArrowRight/></label><label className="capture-action"><input hidden type="file" accept="image/*,video/*" multiple onChange={addFiles}/><ImagePlus/><span><b>Add from device</b><small>Photo or short video</small></span><Plus/></label><button className={`capture-action ${recording?'recording':''}`} onClick={toggleRecording}>{recording?<Pause/>:<Mic/>}<span><b>{recording?'Recording… tap to finish':'Record voice note'}</b><small>Describe the condition hands-free</small></span>{recording?<Square/>:<Plus/>}</button></div>{assets.length>0&&<div className="capture-assets"><h2>{assets.length} item{assets.length!==1?'s':''} added</h2><div>{assets.map((asset,index)=><figure key={asset.url}>{asset.kind==='photo'?<img src={asset.url} alt={`Captured evidence ${index+1}`}/>:asset.kind==='video'?<video src={asset.url} muted playsInline aria-label={`Captured video ${index+1}`}/>:<span><Mic/></span>}<i className="capture-asset-kind">{asset.kind==='video'?<Film/>:asset.kind==='audio'?<Mic/>:<Camera/>}</i><button onClick={()=>removeAsset(index)} aria-label="Remove"><X/></button></figure>)}</div></div>}<div className="capture-tip"><Sparkles/><p><b>Capture tip</b>Include surrounding studs and the entry door in one photo so the location can be independently verified.</p></div></section>}
      {step===3&&<section className="capture-step"><p className="capture-eyebrow">Observation</p><h1>What is different?</h1><p>A short field description is enough. BUILI will structure it and find the relevant project source.</p><label className="capture-note"><span>Field note</span><textarea value={note} onChange={e=>{setNote(e.target.value);setStepError('')}} rows={5} maxLength={500} required/><small>{note.length}/500</small></label><div className="quick-measure"><Ruler/><div><span>Measured elevation <small>(optional)</small></span><label><input aria-label="Measured elevation in inches above finished floor" inputMode="decimal" value={measurement} onChange={e=>{setMeasurement(e.target.value);setStepError('')}}/><b>in. AFF</b></label></div><button type="button" onClick={()=>setMeasurement('')} aria-label="Remove measurement"><X/></button></div><div className="analysis-preview"><Sparkles/><div><b>BUILI will check</b><span>Location · drawing revision · requirement · visual evidence · measurement · missing proof</span></div></div></section>}
      {step===4&&<section className="capture-step"><p className="capture-eyebrow">Review</p><h1>Ready to create the observation.</h1><p>Nothing becomes a formal action until a project reviewer approves it.</p><div className="capture-review"><ReviewRow label="Location" value={`${room} / ${position}`}/><ReviewRow label="Evidence" value={`${assets.length||(demo&&demoEvidenceSelected?4:0)} assets / location confirmed`}/><ReviewRow label="Observation" value={note}/><ReviewRow label="Measurement" value={measurement?`${measurement} in. AFF`:'Not provided'}/></div>{demo&&<div className="capture-ai-result"><div><Sparkles/><span>Preliminary match</span><strong>E1.1 / Electrical Note 3</strong></div><p>Garage receptacles require a minimum mounting elevation of 18 in. AFF. The observed centerline may be 6 in. below the requirement.</p><span><CheckCircle2/> Human review required</span></div>}{saveError&&<p className="form-error">{saveError}</p>}<div className="capture-retention-note"><ShieldCheck/><span><b>Originals and history are retained</b>Files, checksums, analysis versions, and reviewer actions are recorded in the project audit trail under your organization&apos;s retention policy.</span></div></section>}
      {stepError&&<p className="capture-validation" role="alert">{stepError}</p>}
    </main><footer className="capture-footer">{step>1&&<button className="button button--secondary" onClick={()=>{setStepError('');setStep(step-1)}}>Back</button>}<button className="capture-next" disabled={saving} onClick={()=>step<4?continueFlow():save()}>{saving?<><LoaderCircle className="spin"/> Uploading {progress}%</>:step<4?<>Continue <ArrowRight/></>:<>Create observation <Check/></>}</button></footer>
  </div>;
}
function ReviewRow({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b><Check/></div>}
