'use client';

import Image from 'next/image';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, ChevronDown, Circle, ClipboardCheck, Clock3, Download, FileQuestion, FileText, Image as ImageIcon, MapPin, Mic2, MoreHorizontal, Play, Ruler, Send, ShieldCheck, Sparkles, UserRoundCheck } from 'lucide-react';
import { useState } from 'react';
import { Discipline, StatusPill } from './status-pill';
import { demoIssue } from '@/lib/demo-data';

const photos = [
  {src:'/demo/garage-east-wall-context.png',thumb:'/demo/garage-east-wall-context-thumb.webp',label:'Context',alt:'Wide context of the garage east wall and installed GFCI box'},
  {src:'/demo/receptacle-rough-in-detail.png',thumb:'/demo/receptacle-rough-in-detail-thumb.webp',label:'Detail',alt:'Close detail of the GFCI receptacle box between exposed studs'},
  {src:'/demo/box-elevation-measurement.png',thumb:'/demo/box-elevation-measurement-thumb.webp',label:'Measurement',alt:'Tape measurement showing the receptacle box centerline at approximately twelve inches'}
];

export function DemoIssueWorkspace() {
  const [activePhoto,setActivePhoto]=useState(2); const [action,setAction]=useState<'punch'|'rfi'>('punch'); const [tab,setTab]=useState<'overview'|'evidence'|'sources'|'activity'>('overview');
  return <div className="issue-detail">
    <header className="issue-detail-header"><div className="issue-backline"><Link href="/app/issues"><ArrowLeft/> Issues</Link><span>/</span><b>{demoIssue.id}</b></div><div className="issue-titleline"><div><div className="issue-title-meta"><Discipline value="ELEC"/><StatusPill tone="green">Ready for review</StatusPill><span>High priority</span></div><h1>{demoIssue.title}</h1><p><MapPin/> {demoIssue.location} <span/> Reported by Mike Alvarez · 18 min ago</p></div><div className="issue-header-actions"><a className="button button--secondary" href="/demo/BUI-1042-issue-package.pdf" target="_blank" rel="noreferrer"><Download/> Export</a><button className="icon-button"><MoreHorizontal/></button></div></div></header>
    <section className="decision-summary"><div className="decision-icon"><ClipboardCheck/></div><div><span>BUILI recommended action</span><h2>Correct in field before close-in · create punch item</h2><p>The controlling note is clear and the measurement confirms a 6 in. deviation. An RFI is not required unless the team disputes the requirement.</p></div><div className="decision-save"><b>~34 min</b><span>estimated RFI preparation avoided</span></div><CheckCircle2 className="decision-check"/></section>
    <nav className="issue-tabs" aria-label="Issue sections">{(['overview','evidence','sources','activity'] as const).map(name=><button key={name} onClick={()=>setTab(name)} className={tab===name?'active':''}>{name}{name==='evidence'&&<span>4</span>}</button>)}</nav>
    {tab==='overview'&&<div className="issue-detail-grid">
      <div className="issue-primary">
        <section className="evidence-viewer"><div className="evidence-main"><Image src={photos[activePhoto].src} alt={photos[activePhoto].alt} fill sizes="(max-width: 900px) 100vw, 62vw" priority/><span>{activePhoto+1} of 3 · {photos[activePhoto].label}</span></div><div className="evidence-thumbs">{photos.map((photo,index)=><button key={photo.label} className={activePhoto===index?'active':''} onClick={()=>setActivePhoto(index)}><Image src={photo.thumb} alt="" width={180} height={130}/><span>{photo.label}</span></button>)}<button className="audio-thumb" onClick={()=>document.getElementById('voice-evidence')?.scrollIntoView({behavior:'smooth'})}><Mic2/><span>Voice · 0:32</span></button></div></section>
        <section className="verification-narrative"><div><p className="mini-label">Observed condition</p><p>{demoIssue.observed}</p></div><div><p className="mini-label">Current requirement</p><p>{demoIssue.expected}</p><button>Open E-1.1 · Rev 03 · Note 3</button></div><div className="difference-row"><p className="mini-label">Verified difference</p><p>{demoIssue.difference}</p><span><b>{demoIssue.measurement.delta}</b> below minimum</span></div></section>
        <section id="voice-evidence" className="voice-evidence"><div className="voice-player"><button aria-label="Play voice note"><Play fill="currentColor"/></button><div><span className="waveform">{Array.from({length:42}).map((_,i)=><i key={i} style={{height:`${7+(i*7)%20}px`}}/>)}</span><small>00:00 <b/> 00:32</small></div><strong>1×</strong></div><div className="transcript"><div><p className="mini-label">Voice transcript</p><span>Mike Alvarez · Foreman · Captured on site</span></div><p>“{demoIssue.transcript}”</p></div><audio controls preload="metadata"><source src="/demo/foreman-voice-note.mp3" type="audio/mpeg"/><track default kind="captions" src="/demo/foreman-voice-note.vtt" srcLang="en" label="English"/></audio></section>
        <section className="source-citation"><div className="source-title"><FileText/><div><p className="mini-label">Controlling requirement</p><h3>{demoIssue.source.sheet} · Rev {demoIssue.source.revision} · {demoIssue.source.detail}</h3></div><StatusPill tone="green">Current</StatusPill></div><blockquote>“{demoIssue.source.excerpt}”</blockquote><footer><span>Electrical drawings</span><span>Published Jul 8, 2026</span><a href="/demo/cooper-residence-E1.1-demo.pdf" target="_blank" rel="noreferrer">View on sheet</a></footer></section>
      </div>
      <aside className="issue-secondary">
        <section><div className="aside-title"><h2>Evidence sufficiency</h2><strong>Complete</strong></div><div className="sufficiency-score"><b>96</b><span>/100</span><i><em style={{width:'96%'}}/></i></div><CheckRow title="Exact location" value="Garage · east wall"/><CheckRow title="Context and detail" value="2 views captured"/><CheckRow title="Measured condition" value="12 in. AFF"/><CheckRow title="Current requirement" value="E-1.1 Rev 03"/><CheckRow title="Installation state" value="Open before close-in"/><div className="sufficiency-note"><ShieldCheck/><p><b>Safe to act</b>Evidence supports field correction. No material limitation remains.</p></div></section>
        <section><div className="aside-title"><h2>Measurement</h2><Ruler/></div><div className="measurement-compare"><div><span>Observed</span><b>{demoIssue.measurement.observed}</b></div><div><span>Required</span><b>{demoIssue.measurement.required}</b></div><div className="measurement-delta"><span>Deviation</span><b>{demoIssue.measurement.delta}</b></div></div></section>
        <section><div className="aside-title"><h2>Action routing</h2><Sparkles/></div><button className={`action-choice ${action==='punch'?'active':''}`} onClick={()=>setAction('punch')}><span><ClipboardCheck/></span><div><b>Field correction / Punch</b><small>Recommended · requirement is clear</small></div><Check/></button><button className={`action-choice ${action==='rfi'?'active':''}`} onClick={()=>setAction('rfi')}><span><FileQuestion/></span><div><b>Clarification RFI</b><small>Optional · if requirement is disputed</small></div><Circle/></button>{action==='punch'?<div className="action-draft"><label>Responsible trade<select defaultValue="Delta Electrical"><option>Delta Electrical</option></select></label><label>Due before<input value="Wall close-in · Jul 14" readOnly/></label><p>Raise GFCI box to minimum 18 in. AFF centerline and upload completion photo with measurement.</p></div>:<div className="action-draft"><p>Please confirm whether Electrical Note 3 governs the garage east wall GFCI shown on E1.1, and whether Delta Electrical should raise the box before close-in.</p></div>}<button className="button button--primary button--full"><UserRoundCheck/> Send for PM approval</button></section>
      </aside>
    </div>}
    {tab==='evidence'&&<EvidenceTab/>}{tab==='sources'&&<SourcesTab/>}{tab==='activity'&&<ActivityTab/>}
  </div>;
}

function CheckRow({title,value}:{title:string;value:string}){return <div className="check-row"><Check/><span><b>{title}</b><small>{value}</small></span></div>}
function EvidenceTab(){return <div className="detail-tab-panel"><div className="tab-panel-heading"><h2>Evidence chain</h2><p>Four original assets linked to one field location. Checksums preserve file integrity.</p></div><div className="evidence-chain"><ChainItem icon={<ImageIcon/>} title="Garage east wall context" meta="Photo · Mike Alvarez · 4:17 PM"/><ChainItem icon={<ImageIcon/>} title="GFCI rough-in detail" meta="Photo · Mike Alvarez · 4:18 PM"/><ChainItem icon={<Ruler/>} title="Box elevation measurement" meta="Photo + measurement · 12 in. AFF"/><ChainItem icon={<Mic2/>} title="Foreman voice note" meta="Audio · 00:32 · Transcript verified"/></div></div>}
function ChainItem({icon,title,meta}:{icon:React.ReactNode;title:string;meta:string}){return <div className="chain-item"><span>{icon}</span><div><b>{title}</b><small>{meta}</small></div><StatusPill tone="green">Verified</StatusPill></div>}
function SourcesTab(){return <div className="detail-tab-panel"><div className="tab-panel-heading"><h2>Source of truth</h2><p>BUILI resolved the current controlling requirement before classifying the issue.</p></div><div className="source-graph"><div className="source-node current"><FileText/><span><b>E-1.1 · Rev 03</b><small>Current drawing · Jul 8</small></span></div><i>supersedes</i><div className="source-node"><FileText/><span><b>E-1.1 · Rev 02</b><small>Superseded · Jun 21</small></span></div><i>supports</i><div className="source-node evidence"><ImageIcon/><span><b>BUI-1042 evidence set</b><small>Captured Jul 12</small></span></div></div></div>}
function ActivityTab(){return <div className="detail-tab-panel"><div className="tab-panel-heading"><h2>Audit activity</h2><p>Every AI suggestion, human edit, source, and approval is retained.</p></div><div className="issue-timeline"><Timeline icon={<Mic2/>} title="Mike Alvarez created field observation" meta="4:18 PM · 4 evidence assets"/><Timeline icon={<Sparkles/>} title="BUILI analyzed evidence and sources" meta="4:19 PM · Verification run vr_92F1"/><Timeline icon={<ShieldCheck/>} title="Source E-1.1 Rev 03 verified as current" meta="4:20 PM · Confidence 97%"/><Timeline icon={<Clock3/>} title="Jordan Cho moved issue to review" meta="4:27 PM · No content edits"/></div></div>}
function Timeline({icon,title,meta}:{icon:React.ReactNode;title:string;meta:string}){return <div className="timeline-item"><span>{icon}</span><div><b>{title}</b><small>{meta}</small></div></div>}
