'use client';

import { Box, ChevronDown, Crosshair, Layers3, Maximize2, MousePointer2, Rotate3D, ScanLine, Search, SplitSquareHorizontal, ZoomIn, ZoomOut } from 'lucide-react';
import { useEffect, useState } from 'react';
import { StatusPill } from './status-pill';
import { useWorkspace } from './demo-mode';
import { PageHeader } from './page-header';
import { api } from '@/lib/api';

type ViewMode = '2d' | '3d' | 'split' | 'evidence';
const sheets = [
  { discipline:'Architectural', items:[['A-101','Ground floor plan','Rev 04'],['A-202','Level 2 plan','Rev 05'],['A-601','Door schedule','Rev 02']] },
  { discipline:'Electrical', items:[['E1.1','Power & signal plan','Rev 03'],['E5.1','Electrical details','Rev 01']] },
  { discipline:'Mechanical', items:[['M-202','Level 2 mechanical','Rev 03']] }
];

export function SpatialWorkbench() {
  const{demo,projectId}=useWorkspace();
  const [mode,setMode] = useState<ViewMode>('2d'); const [selected,setSelected] = useState('BUI-1042'); const [sheet,setSheet] = useState('E1.1');
  if(!demo)return <LiveSpatialScenes projectId={projectId}/>;
  return <div className="spatial-workbench">
    <aside className="sheet-browser"><div className="panel-title"><b>Project sheets</b><button aria-label="Search sheets"><Search/></button></div><div className="sheet-scroll">{sheets.map(group=><section key={group.discipline}><h3><ChevronDown/> {group.discipline}<span>{group.items.length}</span></h3>{group.items.map(item=><button key={item[0]} onClick={()=>setSheet(item[0])} className={sheet===item[0]?'active':''}><b>{item[0]}</b><span>{item[1]}</span><small>{item[2]}</small></button>)}</section>)}</div><div className="sheet-legend"><span><i className="dot-elec"/> Electrical</span><span><i className="dot-issue"/> Open issue</span></div></aside>
    <section className="viewer-column">
      <div className="viewer-toolbar"><div className="view-tabs"><button className={mode==='2d'?'active':''} onClick={()=>setMode('2d')}><ScanLine/> 2D plan</button><button className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}><Box/> 3D context</button><button className={mode==='split'?'active':''} onClick={()=>setMode('split')}><SplitSquareHorizontal/> Split</button><button className={mode==='evidence'?'active':''} onClick={()=>setMode('evidence')}><Layers3/> Evidence</button></div><div className="viewer-tools"><button title="Select"><MousePointer2/></button><button title="Center view"><Crosshair/></button><button title="Zoom in"><ZoomIn/></button><button title="Zoom out"><ZoomOut/></button><button title="Fullscreen"><Maximize2/></button></div></div>
      <div className={`viewer-canvas viewer-canvas--${mode}`}>
        {(mode==='2d'||mode==='split'||mode==='evidence') && <FloorPlan selected={selected} onSelect={setSelected} evidence={mode==='evidence'}/>}
        {(mode==='3d'||mode==='split') && <SpatialScene selected={selected} onSelect={setSelected}/>}
        <div className="viewer-compass"><span>N</span><i/></div>
        <div className="viewer-scale">1/4&quot; = 1&apos;-0&quot; · Sheet {sheet} · Rev 03</div>
      </div>
    </section>
    <aside className="viewer-inspector"><div className="panel-title"><b>Issue inspector</b><button>...</button></div><div className="inspector-scroll"><p className="inspector-eyebrow">{selected} / Electrical</p><h2>Garage GFCI receptacle below required elevation</h2><StatusPill tone="green">Ready for review</StatusPill><dl><div><dt>Location</dt><dd>Garage / East wall</dd></div><div><dt>Source</dt><dd>E1.1 / Rev 03</dd></div><div><dt>Observed</dt><dd>12 in. AFF centerline</dd></div><div><dt>Required</dt><dd>18 in. AFF minimum</dd></div></dl><section><h3>Spatial confidence</h3><Confidence label="Floor & room" value={99}/><Confidence label="Wall location" value={94}/><Confidence label="Source alignment" value={97}/></section><section><h3>Finding</h3><p>The installed box appears 6 in. below Electrical Note 3. The open stud bay allows correction before close-in.</p></section><div className="inspector-callout"><b>Evidence sufficient</b><span>Context, detail, measurement, time, and location are present.</span></div></div><div className="inspector-actions"><button className="button button--secondary">Open issue</button><button className="button button--primary">Start punch item</button></div></aside>
  </div>;
}

type Scene={id:string;source_revision_id:string;version:number;status:string;confidence_json:Record<string,unknown>;created_at:string};
function LiveSpatialScenes({projectId}:{projectId:string}){const[scenes,setScenes]=useState<Scene[]>([]);const[error,setError]=useState('');useEffect(()=>{if(!projectId||['loading','none'].includes(projectId))return;let active=true;api.get<Scene[]>(`/projects/${projectId}/spatial-scenes`).then(data=>{if(active)setScenes(data)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Spatial scenes could not be loaded.')});return()=>{active=false}},[projectId]);return <div className="page-pad"><PageHeader title="Drawings & 3D" description="Approved spatial scene versions generated from the project drawing record."/>{error&&<p className="inline-error">{error}</p>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Scene</th><th>Source revision</th><th>Version</th><th>Status</th><th>Created</th></tr></thead><tbody>{scenes.map(scene=><tr key={scene.id}><td className="cell-id">{scene.id}</td><td className="cell-id">{scene.source_revision_id}</td><td>v{scene.version}</td><td><StatusPill tone={scene.status==='approved'?'green':scene.status==='failed'?'red':'blue'}>{scene.status}</StatusPill></td><td className="cell-muted">{new Date(scene.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>{scenes.length===0&&!error&&<div className="live-placeholder"><Box/><p><b>No spatial scene is available yet.</b><span>Process a drawing revision to create a plan graph and lightweight 3D scene.</span></p></div>}</div>}

function FloorPlan({selected,onSelect,evidence}:{selected:string;onSelect:(id:string)=>void;evidence:boolean}) { return <svg className="floor-plan" viewBox="0 0 820 560" aria-label="Electrical floor plan"><g className="fp-walls"><path d="M80 70h660v410H80zM80 270h190V70m0 200h190V70m0 200h280M270 270v210m190-210v210M610 270v210"/><path d="M110 70v20m100-20v20m60 120h20m170-50h20m130 110h20M610 400h20"/></g><g className="fp-labels"><text x="103" y="105">GARAGE</text><text x="292" y="105">ENTRY</text><text x="483" y="105">KITCHEN</text><text x="103" y="303">STORAGE</text><text x="292" y="303">HALL</text><text x="483" y="303">LIVING</text><text x="633" y="303">OFFICE</text><text x="103" y="122">EAST WALL</text></g><g className="fp-electrical"><circle cx="252" cy="168" r="5"/><path d="m246 168 12 0M252 162v12"/><circle cx="518" cy="173" r="5"/><path d="m512 173 12 0M518 167v12"/><circle cx="690" cy="350" r="5"/></g>{evidence&&<g className="fp-evidence-cone"><path d="M214 231 252 168 298 232Z"/><circle cx="214" cy="231" r="5"/></g>}<g onClick={()=>onSelect('BUI-1042')} className={`fp-pin ${selected==='BUI-1042'?'selected':''}`} transform="translate(252 168)"><circle r="18"/><circle r="5"/><text x="25" y="5">BUI-1042</text></g><g onClick={()=>onSelect('BUI-1038')} className={`fp-pin fp-pin--amber ${selected==='BUI-1038'?'selected':''}`} transform="translate(610 376)"><circle r="14"/><circle r="4"/></g></svg>; }
function SpatialScene({selected,onSelect}:{selected:string;onSelect:(id:string)=>void}) { return <div className="spatial-scene"><svg viewBox="0 0 820 560"><g className="iso-floor"><path d="m133 362 320-186 246 142-320 187z"/></g><g className="iso-walls"><path d="M133 180v182l320-186V44zM453 44v132l246 142V187z"/><path d="m235 302 0-122 85-49v121M485 196V93l88 51v102M602 263V161l59 34v103"/></g><g className="iso-objects"><path d="m250 311 45-26 26 15-45 26zM496 314l87-50 55 32-87 50z"/><path d="m394 222 44-25v64l-44 25z"/></g><g onClick={()=>onSelect('BUI-1042')} className={`iso-pin ${selected==='BUI-1042'?'selected':''}`} transform="translate(237 246)"><circle r="14"/><path d="M0 14v44"/><circle cy="58" r="3"/></g></svg><div className="scene-hint"><Rotate3D/> Drag to orbit · Scroll to zoom</div></div>; }
function Confidence({label,value}:{label:string;value:number}){return <div className="confidence-row"><span>{label}</span><i><b style={{width:`${value}%`}}/></i><em>{value}%</em></div>}
